################## get all products ##################
# GET http://localhost:3000/api/v1/products HTTP/1.1



################## create a new product ##################
# POST http://localhost:3000/api/v1/product/new HTTP/1.1
# Content-Type: application/json

# {
#     "name":"second product",
#     "description": "this is second product",
#     "price": 100,
#     "images": {"publicId":"pid","url":"url"},
#     "category": "mobile"
# }

################## update product ##################
# PUT  http://localhost:3000/api/v1/product/6200b1fc8cb5ca6b6b0f7747 HTTP/1.1
# Content-Type: application/json

# {
#     "name": "product2",
#     "description": "this is product2",
#     "price": 2300,
#     "images": {"publicId":"pid","url":"url"},
#     "category": "laptop"
# }

################# update product rating ##################
# PUT  http://localhost:3000/api/v1/review HTTP/1.1
# Content-Type: application/json

# {
#  "productId":"6200b1bf8cb5ca6b6b0f7744",
#  "rating":4,
#  "comment":"what a wonderfull product"
# }

################## get all reviews ##################
# GET  http://localhost:3000/api/v1/reviews?id=6211e9a6e7272492a614ed34 HTTP/1.1

################## delete review ##################
# DELETE http://localhost:3000/api/v1/review?id=6211eca6560b15d3b23b9296&productId=6200b1bf8cb5ca6b6b0f7744 HTTP/1.1

# ################## delete product ##################
# DELETE  http://localhost:3000/api/v1/product/6200b1fc8cb5ca6b6b0f7747 HTTP/1.1
# Content-Type: application/json

# ################## get one product ##################
# GET  http://localhost:3000/api/v1/product/6200b1bf8cb5ca6b6b0f7744 HTTP/1.1
# Content-Type: application/json


# #####################################################
# ################## user routes     ##################
# #####################################################
# ################## registor a user    ##################
# POST http://localhost:3000/api/v1/register HTTP/1.1
# Content-Type: application/json

# {
#     "name":"altamish",
#     "email":"altamishpasha@gmail.com",
#     "password":"123456789"
# }

################## login user    ##################
# POST http://localhost:3000/api/v1/login HTTP/1.1
# Content-Type: application/json

# {
#     "email":"altamishpasha@gmail.com",
#     "password":"1234567890"
# }

# ################## logout user    ##################
# GET  http://localhost:3000/api/v1/logout HTTP/1.1


# ################## send password reset link ##################
# POST  http://localhost:3000/api/v1//password/forget HTTP/1.1
# Content-Type: application/json

# {
#     "email":"altamishpasha@gmail.com"
# }

# ################## reset password ##################
# PUT  http://localhost:3000/api/v1/password/reset/0423a3a93497556f9d5281917add865da937d6db HTTP/1.1
# Content-Type: application/json

# {
#     "password":"1234567890",
#     "confirmPassword":"1234567890"
# }

# ################## get user details ##################
# GET   http://localhost:3000/api/v1/me HTTP/1.1


# ################## update password ##################
# PUT  http://localhost:3000/api/v1/password/update HTTP/1.1
# Content-Type: application/json

# {
#     "oldPassword":"00000000001",
#     "newPassword":"0000000000",
#     "confirmPassword":"0000000000"
# }

# ################## update profile ##################
# PUT  http://localhost:3000/api/v1/me/update HTTP/1.1
# Content-Type: application/json

# {
#     "name":"new name",
#     "email":"pasha@gmail.com"
# }

################## get all users (admins)##################
# GET  http://localhost:3000/api/v1//admin/users HTTP/1.1

################## get single user (admins)##################
# GET  http://localhost:3000/api/v1//admin/user/6208ecc6ac93f2954e035767 HTTP/1.1


# ################## update user role ##################
# PUT  http://localhost:3000/api/v1/admin/user/6208ecc6ac93f2954e035767 HTTP/1.1
# Content-Type: application/json

# {
#     "name":"new name",
#     "email":"pasha@gmail.com",
#     "role":"admin"
# }


# ################## update profile ##################
# DELETE  http://localhost:3000/api/v1/admin/user/620600f238602b076331f25e HTTP/1.1



# ################## new order ##################
# POST   http://localhost:3000/api/v1/order/new HTTP/1.1
# Content-Type: application/json

# {
#     "shippingInfo":{"address":"hatawwa patty","city":"amroha","state":"up","country":"india","pinCode":"244222","phoneNumber":"9832759874358"},
#      "orderItems":[{"product":"621218ef039da96a9c3b8c3e","name":"first product","price":200,"image":"image","quantity":2}],
#      "paymentInfo":{"id":"orderid","status":"paid"},
#      "itemsPrice":200,
#      "taxPrice":23,
#      "shippingPrice":24,
#      "totalPrice":247
# }

# ################## get single order ##################
# GET http://localhost:3000/api/v1/order/621223804b35367f8a04b999 HTTP/1.1

# ################## get all order for loged in user ##################
# GET http://localhost:3000/api/v1/orders/me HTTP/1.1


# ################## get all orders (admin) ##################
# GET http://localhost:3000/api/v1/admin/orders HTTP/1.1

# # ################## update order (admin) ##################
# PUT  http://localhost:3000/api/v1/admin/order/621223804b35367f8a04b999 HTTP/1.1
# Content-Type: application/json

# {
#     "status":"Delevered"
# }


# ################## delete order (admin) ##################
DELETE  http://localhost:3000/api/v1/admin/order/621223804b35367f8a04b999 HTTP/1.1
